# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: Build-Check
jobs:
  build-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-22.04,   r: '4.3'}
          - {os: ubuntu-20.04,   r: '4.2'}

    env:
      R_KEEP_PKG_SOURCE: yes
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      # CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install System Dependencies
        if: runner.os == 'Linux'
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04"))')

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true
          Ncpus: 4

      - name: Get HCA Dependancies From PPM
        run: |
          remotes::install_github("happycabbage/hcapipelines2")
          remotes::install_github("happycabbage/hcatools")

      - name: Install R Dependencies
        run: |
          install.packages("rcmdcheck")
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Build R Package
        uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual", "--install-args=--build")'
          check-dir: '"check"'

      - name: Post Coverage Report
        run: |
          covr::codecov(quiet = FALSE, clean = FALSE, install_path = file.path(Sys.getenv("RUNNER_TEMP"), "package"))
        shell: Rscript {0}


        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PPM_HOST }}
          username: ${{ secrets.PPM_USER }}
          key: ${{ secrets.PPM_KEY }}
          port: ${{ secrets.PPM_PORT }}
          script: |
            rspm add --source=local-src \
                --path=check/hcadscore_source.tar.gz \
                --succeed-on-existing
            rspm add binary --source=local-src --distribution=focal \
                --path=check/hcadscore_binary.tar.gz \
                --succeed-on-existing
            rm -rf check

        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.PPM_HOST }}
          username: ${{ secrets.PPM_USER }}
          key: ${{ secrets.PPM_KEY }}
          port: ${{ secrets.PPM_PORT }}
          source: check/*
          target: .
