test_that("App Utils", {
  # get_app_dir()
  # get_app_colors()
  # create_session_dir()
  # clean_session_dir()
  # save_plot_data()
  # generate_report()
  # save_ggplots()
  # build_scenario_data()
  # save_ml_context()
  # exec_ml_restock()
  # default_ml_params()
  # scale_ml_params()
  # unscale_ml_params()
})
